[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
  force = true
  methods = ["POST"]

[functions]
node_bundler = "esbuild"
external_node_modules = ["symbol-sdk"]
